name: CI/CD
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Lint with pylint
        run: |
          set -e
          poetry run pylint frequen_c_backend/ tests/
      - name: Lint with mypy
        run: |
          set -e
          poetry run mypy .
      - name: Lint with black
        run: |
          set -e
          poetry run black . --check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Create .env
        run: |
          touch .env
          echo "FLASK_APP=\"frequen_c_backend\"" >> .env
          echo "FLASK_ENV=\"production\"" >> .env
      - name: Test with pytest
        run: |
          set -e
          poetry run pytest
